import { Badge } from "@/components/ui/badge";

/**
 * Reference data in this system ships unverified. Anywhere a value, a cluster
 * name or a clause reference is shown, the screen has to say so — a placeholder
 * presented without a marker reads as authoritative.
 */
export function UnverifiedNotice({
  title,
  body,
}: {
  title: string;
  body: string;
}) {
  return (
    <div className="mb-4 border border-amber-400 bg-amber-50 px-3 py-2.5 text-[12px] text-amber-950">
      <div className="flex flex-wrap items-center gap-2">
        <Badge tone="draft">Unverified</Badge>
        <span className="font-semibold">{title}</span>
      </div>
      <p className="mt-1.5 max-w-3xl leading-relaxed text-amber-900">{body}</p>
    </div>
  );
}

export function ClusterSourceNotice({
  clusterSource,
  clustersVerified,
  clusterCount,
}: {
  clusterSource: string;
  clustersVerified: boolean;
  clusterCount: number;
}) {
  if (clustersVerified) {
    return (
      <div className="mb-4 border border-emerald-300 bg-emerald-50 px-3 py-2.5 text-[12px] text-emerald-900">
        <Badge tone="ok">Verified</Badge>
        <span className="ml-2">
          {clusterCount} notified cluster(s), read back against the published list.
        </span>
        <p className="mt-1.5 leading-relaxed">{clusterSource}</p>
      </div>
    );
  }
  return (
    <UnverifiedNotice
      title="This notified cluster list is UNVERIFIED and must not be relied on for an eligibility determination"
      body={
        `${clusterCount} cluster(s) are held for this sector. No row has been read back against the ` +
        `official BEE list. A match found here is a prompt to check the published list, not an ` +
        `eligibility decision. Source note on record: ${clusterSource}`
      }
    />
  );
}

/**
 * Nothing this system renders is a BEE or ICM form. Shown next to every report
 * download so a generated PDF is never mistaken for a filing.
 */
export function ReportDisclaimer() {
  return (
    <p className="mt-2 max-w-3xl text-[11px] leading-relaxed text-stone-500">
      Generated by VerifyStack from the evidence and runs held in this engagement. It is a working
      document, not an official BEE or ICM form, and it has not been prepared on, or validated
      against, any prescribed template.
    </p>
  );
}
